/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finamproject;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    String ImgPath = null;
    ResizeImage img = new ResizeImage();

    /**
     * Creates new form login
     */
    Timer tm;
    int x = 0;
    String[] list = {
        "C:/Users/Admin/Desktop/Image project/images_013.jpg",
        "C:/Users/Admin/Desktop/Image project/images_021.jpg",
        "C:/Users/Admin/Desktop/Image project/5756e70920db5-coiffure-type-afro-pour-homme.jpg",
        "C:/Users/Admin/Desktop/Image project/75d32d4f0e722b7493096a8b8f16d88c.jpg",
        "C:/Users/Admin/Desktop/Image project/5756e6ce00e65-coupe-cheveux-homme.jpg",
        "C:/Users/Admin/Desktop/Image project/images_098.jpg",
        "C:/Users/Admin/Desktop/Image project/images_089.jpg",
        "C:/Users/Admin/Desktop/Image project/images_157.jpg"

    };

    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        imageIcon.setIcon(img.ResizeImage("C:\\Users\\Admin\\Desktop\\Image project\\demo-team-member.jpg", null, jimage.getWidth(), jimage.getHeight()));
        // jLabel13.setIcon(img.ResizeImage("C:\\Users\\Admin\\Desktop\\Arobase.jpg", null, jLabel13.getWidth(), jLabel13.getHeight()));

        SetImageSize(7);
        tm = new Timer(2500, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SetImageSize(x);
                x += 1;
                if (x >= list.length) {
                    x = 0;
                }
            }
        });
        tm.start();
    }

    Connecter connect = new Connecter();
    Connection con = connect.getConnect();

    public void SetImageSize(int i) {
        ImageIcon icon = new ImageIcon(list[i]);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(jimage.getWidth(), jimage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImc = new ImageIcon(newImg);
        jimage.setIcon(newImc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jimage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jlogin = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        txt_lpassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_email1 = new javax.swing.JTextField();
        txt_quater = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        txt_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_zipcode = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        imageIcon = new javax.swing.JLabel();
        txt_town = new javax.swing.JComboBox();
        txt_saloonName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane.setBackground(new java.awt.Color(255, 51, 51));
        jTabbedPane.setToolTipText("");
        jTabbedPane.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel11.setText("Password :");

        txt_email.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N

        jlogin.setBackground(new java.awt.Color(102, 255, 102));
        jlogin.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jlogin.setForeground(new java.awt.Color(255, 255, 255));
        jlogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ICON\\1484958226_Key.png")); // NOI18N
        jlogin.setText("Login");
        jlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jloginMouseClicked(evt);
            }
        });
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jCheckBox2.setText("See Password");
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });

        txt_lpassword.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(txt_lpassword))
                .addGap(85, 85, 85)
                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
            .addComponent(jimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jimage, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlogin)
                .addGap(10, 10, 10))
        );

        jTabbedPane.addTab("Login", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel1.setText("Email :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 51, 25);

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel2.setText("Town :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 110, 52, 25);

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel3.setText("Description :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 220, 99, 25);

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel4.setText("Quater :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 150, 63, 25);

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel7.setText("Contact :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 300, 70, 25);

        jLabel8.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel8.setText("Password :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 350, 85, 25);

        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel9.setText("Saloon_Image :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 450, 121, 25);

        txt_email1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txt_email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_email1FocusLost(evt);
            }
        });
        jPanel1.add(txt_email1);
        txt_email1.setBounds(286, 10, 340, 30);

        txt_quater.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jPanel1.add(txt_quater);
        txt_quater.setBounds(287, 150, 340, 30);

        txt_contact.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jPanel1.add(txt_contact);
        txt_contact.setBounds(287, 300, 340, 30);

        txt_description.setColumns(20);
        txt_description.setRows(5);
        jScrollPane1.setViewportView(txt_description);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(287, 190, 340, 96);

        txt_password.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jPanel1.add(txt_password);
        txt_password.setBounds(287, 350, 340, 30);

        jButton1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 540, 330, 20);

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel5.setText("Zip code :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 570, 100, 25);

        txt_zipcode.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jPanel1.add(txt_zipcode);
        txt_zipcode.setBounds(290, 570, 330, 30);

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ICON\\1484913691_Save.png")); // NOI18N
        jButton2.setText("Save");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(750, 550, 130, 41);

        jCheckBox1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jCheckBox1.setText("See Password");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(710, 360, 120, 30);
        jPanel1.add(imageIcon);
        imageIcon.setBounds(290, 400, 330, 140);

        txt_town.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        txt_town.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bafoussam", "Buea", "Douala", "Yaounde", "Bamenda", "Dschang" }));
        jPanel1.add(txt_town);
        txt_town.setBounds(290, 110, 340, 30);

        txt_saloonName.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txt_saloonName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_saloonNameFocusGained(evt);
            }
        });
        jPanel1.add(txt_saloonName);
        txt_saloonName.setBounds(286, 60, 340, 30);

        jLabel6.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel6.setText("Saloon_Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 60, 118, 25);

        jLabel12.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 102));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(710, 10, 220, 30);

        jTabbedPane.addTab("Create anf account", jPanel1);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ICON\\1484913550_Home.png")); // NOI18N
        jMenu3.setText("Home");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        if (jCheckBox1.isSelected()) {
            txt_password.setEchoChar((char) 0);
        } else {
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            imageIcon.setIcon(img.ResizeImage(path, null, imageIcon.getWidth(), imageIcon.getHeight()));
            ImgPath = path;
        } else {
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txt_email1.getText().isEmpty() || txt_saloonName.getText().isEmpty() || txt_town.getSelectedItem().toString().isEmpty() || txt_quater.getText().isEmpty() || txt_description.getText().isEmpty() || txt_contact.getText().isEmpty() || txt_password.getText().isEmpty() || txt_zipcode.getText().isEmpty() || ImgPath == null) {
            JOptionPane.showMessageDialog(null, "One or more field are empty");
        } else if (!txt_zipcode.getText().isEmpty()) {

            try {
                PreparedStatement p = con.prepareStatement("SELECT id FROM zipCode where zip_code = ?");
                p.setString(1, txt_zipcode.getText());
                ResultSet r1 = p.executeQuery();
                if (r1.next()) {
                    try {
                        PreparedStatement p2 = con.prepareStatement("SELECT * FROM service_provider where email = ? ");
                        p2.setString(1, txt_email1.getText());
                        ResultSet r2 = p2.executeQuery();
                        if (r2.next()) {
                            JOptionPane.showMessageDialog(null, "The Email already exist");
                        } else {
                            try {

                                PreparedStatement ps = con.prepareStatement("INSERT INTO service_provider(email,saloonName,town,quater,description,contact,password,saloonImage)"
                                        + "values(?,?,?,?,?,?,?,?) ");
                                ps.setString(1, txt_email1.getText());
                                ps.setString(2, txt_saloonName.getText());
                                ps.setString(3, txt_town.getSelectedItem().toString());
                                ps.setString(4, txt_quater.getText());
                                ps.setString(5, txt_description.getText());
                                ps.setString(6, txt_contact.getText());
                                ps.setInt(7, txt_password.getText().hashCode());

                                InputStream img = new FileInputStream(new File(ImgPath));
                                ps.setBlob(8, img);

                                ps.executeUpdate();

                                JOptionPane.showMessageDialog(null, "Account create sucessfully");
                                jLabel12.setText("");
                                try {

                                    PreparedStatement ps2 = con.prepareStatement("DELETE FROM zipcode WHERE zip_code = ?");
                                    ps2.setString(1, txt_zipcode.getText());
                                    ps2.executeUpdate();

                                } catch (SQLException ex) {

                                    JOptionPane.showMessageDialog(null, ex.getMessage());
                                }
                                txt_email1.setText("");
                                txt_saloonName.setText(" ");
                                txt_quater.setText(" ");
                                txt_description.setText(" ");
                                txt_contact.setText(" ");
                                txt_password.setText("");
                                txt_zipcode.setText(" ");
                                imageIcon.setIcon(null);

                            } catch (Exception ex) {
                                JOptionPane.showMessageDialog(null, ex.getMessage());
                            }
                        }

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "zip code incorrect contact the administrator");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        new NewJFrame().setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        if (jCheckBox2.isSelected()) {
            txt_lpassword.setEchoChar((char) 0);
        } else {
            txt_lpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed

        if (txt_email.getText().isEmpty() || txt_lpassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "One or more field are empty");
        } else {
            try {

                PreparedStatement p = con.prepareStatement("SELECT * FROM service_provider where email = ?");
                p.setString(1, txt_email.getText());
                ResultSet r = p.executeQuery();

                if (r.next()) {
                    String email = txt_email.getText();
                    new admin(email).setVisible(true);
                    this.hide();
                } else {
                    JOptionPane.showMessageDialog(null, "The Email or Password are incorrect");
                }
            } catch (SQLException ex) {
                System.err.println(ex);
            }
        }
    }//GEN-LAST:event_jloginActionPerformed

    private void jloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginMouseClicked

    }//GEN-LAST:event_jloginMouseClicked

    private void txt_email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_email1FocusLost
        // TODO add your handling code here:
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Matcher matcher = pattern.matcher(txt_email1.getText());
        if (matcher.matches()) {
            jLabel12.setForeground(Color.green);
            jLabel12.setText("The email is  correct");
            jButton2.setEnabled(true);
        } else {
            jLabel12.setForeground(Color.red);
            jLabel12.setText("The email is not correct");
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_txt_email1FocusLost

    private void txt_saloonNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_saloonNameFocusGained
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Matcher matcher = pattern.matcher(txt_email1.getText());
        if (matcher.matches()) {
            jLabel12.setForeground(Color.green);
            jLabel12.setText("The email is  correct");
            jButton2.setEnabled(true);
        } else {
            jLabel12.setForeground(Color.red);
            jLabel12.setText("The email is not correct");
            jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_txt_saloonNameFocusGained

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel jimage;
    private javax.swing.JButton jlogin;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextArea txt_description;
    public javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JPasswordField txt_lpassword;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_quater;
    private javax.swing.JTextField txt_saloonName;
    private javax.swing.JComboBox txt_town;
    private javax.swing.JTextField txt_zipcode;
    // End of variables declaration//GEN-END:variables

}
